Feature/excluded packs
telegram-ru/ru-bot pull request #46
Opened 2018-01-27 04:44 UTC by Piterden

2018-01-27 13:28 UTC, sergeysova requested changes

2018-01-27 13:28 UTC, sergeysova commented on src/lib/telegram-group.js
> +   * @return {{ remove: boolean, restrict: boolean, allowedStickerPacks: Array }}
Add generic parameter for `Array`

2018-01-28 00:50 UTC, Piterden commented on src/lib/telegram-group.js
> +   * @return {{ remove: boolean, restrict: boolean, allowedStickerPacks: Array }}
Original text: Add generic parameter for Array

Translation: Добавить общий параметр для массива en

Не вкурил(

2018-01-28 00:52 UTC, sergeysova commented on src/lib/telegram-group.js
> +   * @return {{ remove: boolean, restrict: boolean, allowedStickerPacks: Array }}
нужно дженерик параметр добавить

2018-01-28 00:53 UTC, Piterden commented on src/lib/telegram-group.js
> +   * @return {{ remove: boolean, restrict: boolean, allowedStickerPacks: Array }}
`string|number`

2018-01-28 00:55 UTC, sergeysova commented on src/lib/chatlist-validate.js
> + * @return {bool|void}
в случае `throw` из функции не возвращается ничего

2018-01-28 00:55 UTC, sergeysova commented on src/lib/chatlist-validate.js
> + * @param {Object} list
Надо указывать какой именно тип.

2018-01-28 00:56 UTC, Piterden commented on src/lib/chatlist-validate.js
> + * @return {bool|void}
`void` и есть ничего.
Они никогда не указываются?

2018-01-28 00:56 UTC, sergeysova commented on src/lib/chatlist-validate.js
> + * @return {Object}
Соотв-но, здесь тоже нужны конкретные типы. Ибо из описания не понятно чем объект из параметра отличается от выходного

2018-01-28 00:57 UTC, sergeysova commented on src/lib/runtime.js
> +  // extend the context methods before features
```
// extend the context methods before install features
```

2018-01-28 00:59 UTC, sergeysova commented on src/lib/telegram-group.js
> +const debug = require('debug')
Раз уж предполагается переименование, то лучше назвать `createDebug`

`Debug` подразумевался как конструктор

2018-01-28 01:00 UTC, Piterden commented on src/lib/chatlist-validate.js
> + * @param {Object} list
Покажи плиз пример

2018-01-28 01:00 UTC, sergeysova commented on src/lib/telegram-group.js
> +   * @param {Object} bot The bot instance
тут наверное есть смысл указать инстанс бота

2018-01-28 01:01 UTC, sergeysova commented on src/lib/telegram-group.js
> +   * { remove: boolean, restrict: boolean, allowedStickerPacks: Array }
такой объект можно сконструировать выше через `@typedef {Object} OptionsObject`

2018-01-28 01:01 UTC, sergeysova commented on src/lib/telegram-group.js
>     * @return {Promise<boolean>}
`bool` or `boolean` ?

2018-01-28 01:02 UTC, sergeysova commented on src/lib/text.js
> +    .filter(Boolean)
👍

2018-01-28 01:02 UTC, sergeysova commented on src/models/index.js
> +  .filter((file) => (!file.startsWith('.')) && (file !== basename) && (file.endsWith('.js')))
👍

2018-01-28 01:03 UTC, Piterden commented on src/lib/telegram-group.js
> +const debug = require('debug')
+

2018-01-28 01:04 UTC, Piterden commented on src/lib/telegram-group.js
> +   * @param {Object} bot The bot instance
Bot - конструктор
bot - экземпляр

2018-01-28 01:04 UTC, sergeysova commented on src/lib/extended-context.js
> +function newHammer() {
Здесь лучше переименовать в `createHammer()`

Но в `bot.context` сразу вставлять инстанс

2018-01-28 01:04 UTC, sergeysova commented on src/lib/extended-context.js
```js
bot.context.hammer = createHammer()
```

или

```js
bot.context.hammer = new Hammer(bot.context)
```

2018-01-28 01:05 UTC, Piterden commented on src/lib/extended-context.js
> +function newHammer() {
Да

2018-01-28 01:06 UTC, Piterden commented on src/lib/extended-context.js
Второе!!!

И везде так!

2018-01-28 01:06 UTC, sergeysova commented on src/lib/chatlist-validate.js
> +          allowedStickerPacks: [],
Сама фича по разрешенным стикер пакам ещё не готова?

Может вынести тогда общие правки в отдельный ПР? (или правки по стикерпакам)

2018-01-28 01:06 UTC, Piterden commented on src/lib/telegram-group.js
>     * @return {Promise<boolean>}
Давай полное везде

2018-01-28 01:07 UTC, Piterden commented on src/lib/chatlist-validate.js
> +          allowedStickerPacks: [],
Поможешь разделить? Я парюсь еще...

2018-01-28 01:25 UTC, sergeysova commented on src/lib/telegram-group.js
> +   * @param {Object} bot The bot instance
не в описаниях типов

2018-01-28 01:26 UTC, sergeysova commented on src/lib/chatlist-validate.js
> + * @param {Object} list
ну например

```js
/**
 * @param {{ key1: string, key2: number }} param
 */
```

2018-01-28 01:26 UTC, Piterden commented on src/lib/telegram-group.js
> +   * @param {Object} bot The bot instance
Gotcha now

2018-01-28 01:28 UTC, sergeysova commented on src/lib/chatlist-validate.js
> + * @return {bool|void}
`void` указывается в двух случаях:

- когда функция не имеет `return` вообще (можно конечно и `@return` не указывать в jsdoc)
- и когда функция имеет явный "пустой" `return` или `return undefined`

В случае `throw` функция не имеет никакого `return`

2018-01-28 01:29 UTC, sergeysova commented on src/lib/telegram-group.js
> +   * @return {{ remove: boolean, restrict: boolean, allowedStickerPacks: Array }}
Зачем строка?

2018-01-28 11:26 UTC, sergeysova commented
@github Why issues closes?

2018-01-28 21:01 UTC, Piterden commented
@github It's very strange. He is not closing it

2018-01-28 21:03 UTC, sergeysova commented
Wtf.

2018-01-28 21:20 UTC, sergeysova commented
@Piterden will I fix it?

2018-02-02 01:29 UTC, Piterden commented on src/lib/telegram-group.js
> +   * @return {{ remove: boolean, restrict: boolean, allowedStickerPacks: Array }}
Так не только id, но и name пака

2018-02-02 07:45 UTC, sergeysova commented on src/features/bot-participation/index.js
> +  const hammer = ctx.newHammer()
```js
const { hammer } = ctx
```

2018-02-02 07:45 UTC, sergeysova commented on src/lib/chatlist-validate.js
> + * @param {{ [string]: number }} list
`@param {{ [name: string]: number } | { [name: string]: { id: number }} list`

2018-02-02 07:45 UTC, sergeysova commented on src/lib/chatlist-validate.js
> + * @return {{ [string]: { id: number } }}
`@return {{ [name: string]: number }}`

2018-02-02 07:45 UTC, sergeysova commented on src/lib/chatlist-validate.js
> +    acc[name] = typeof list[name] === 'number' ? {
никогда не записывай тернарки в таком виде

2018-02-02 07:51 UTC, sergeysova commented on src/lib/chatlist-validate.js
> +    acc[name] = typeof list[name] === 'number' ? {
```js
acc[name] = typeof list[name] === 'number'
  ? {
    // keys
  }
  : list[name]
```

2018-02-02 07:51 UTC, sergeysova commented on src/lib/extended-context.js
> +function newHammer() {
!

2018-02-02 07:51 UTC, sergeysova commented on src/lib/runtime.js
> +const ms = 1000
Если уж выносишь в константы, то пиши их константами в UPPER_CASE и с полным именем описывающим назначение

2018-02-02 07:51 UTC, sergeysova commented on src/lib/string.js
> +  makeName: ({ first_name: firstName, last_name: lastName }) => `${firstName}${lastName ? ` ${lastName}` : ''}`,
Не надо записывать так экспорт. В этом файле в будущем появятся другие функции и они могут переиспользовать друг друга. В записи экспорта объектом, переиспользование выглядит криво.

2018-02-02 07:51 UTC, sergeysova commented on src/lib/telegram-group.js
> +const debug = require('debug')
!

2018-02-02 07:51 UTC, sergeysova commented on src/lib/telegram-group.js
> +      { remove: false, restrict: false, allowed: [] },
Объекты с опциями описывающими начальное значение, лучше писать в столбик

2018-02-02 07:51 UTC, sergeysova commented on src/lib/telegram-group.js
> +      this.admins.nextUpdate = Date.now() + ADMIN_TIMEOUT
ADMIN_TIMEOUT не говорит ни о чем.

— Что за таймаут есть у админов?

именование функций, классов и констант предполагается в стиле большее-меньшее

2018-02-02 08:01 UTC, sergeysova requested changes

2018-02-02 08:01 UTC, sergeysova commented on src/lib/telegram-group.js
> +    this.debug(`isAdmin(${user})`)
такая запись выведет в консоль `isAdmin([Object object])` это не то, что хочется получить

2018-02-02 08:01 UTC, sergeysova commented on src/lib/telegram-group.js
> +    this.debug(`isAdmin(${user})`)
![image](https://user-images.githubusercontent.com/5620073/35722523-b3f62ece-0807-11e8-8d3f-891e53454da3.png)

2018-02-02 08:01 UTC, sergeysova commented on src/lib/telegram-group.js
> +    this.debug(`sendMessage(${{ message, extra }})`)
Здесь также, в консоли будут неинформативные и ненужные сообщения.

2018-02-02 08:01 UTC, sergeysova commented on src/lib/telegram-group.js
> +    this.debug(`sendMessage(${{ message, extra }})`)
![image](https://user-images.githubusercontent.com/5620073/35722576-f624d8cc-0807-11e8-8c5c-9f8fcad516e0.png)
сравни

2018-02-02 08:01 UTC, sergeysova commented on src/lib/telegram-group.js
> +    this.debug(`sendMessage(${{ message, extra }})`)
В общем надо вернуть все `debug` вызовы обратно в стиль множества параметров, вместо приведения к строке

2018-02-02 08:01 UTC, sergeysova commented on src/lib/telegram-group.js
> +    this.debug(`sendMessage(${{ message, extra }})`)
![image](https://user-images.githubusercontent.com/5620073/35722660-42640f3c-0808-11e8-8f41-74f1bce880f5.png)
можно попробовать такую запись, но я не уверен в какой версии ноды она появилась и как работает с ней npmjs.com/debug

2018-02-02 08:04 UTC, sergeysova commented on src/lib/telegram-group.js
> +   * @return {Array}
асинхронные функции всегда возвращают промис и это должно быть 
описано в jsdoc как `{Promise<T>}`

в данном случае `@return {Promise<Array<TelegramUser>>}`

2018-02-02 08:05 UTC, sergeysova commented on src/lib/telegram-group.js
> +   * @return {boolean}
`@return {Promise<boolean>}`

2018-02-08 12:51 UTC, sergeysova commented
@Piterden  ?

2018-02-13 13:06 UTC, sergeysova commented
@Piterden ?

2018-02-28 12:04 UTC, sergeysova commented
@Piterden has any progress?

2018-05-10 12:05 UTC, sergeysova commented
@Piterden please, resolve conflicts.

2018-05-14 21:00 UTC, closed without merging